/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2020-04-29 16:19:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.AdminPanel;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminpanel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"errorpage.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <title>Unique Housing Society</title>\r\n");
      out.write("  \r\n");
      out.write("  <meta name=\"description\" content=\"website description\" />\r\n");
      out.write(" <meta name=\"Keywords\" content=\"Unique housing soceity pune, Unique housing society by laws,housing society, unique housing society legal compliances, unique housing society accounting pune, unique information of housing societies pune, housing society accounting s/w, housing society consultancy, unique housing society taxation managemet, housing society audit, pune, Unique housing society sale/rent,pune\"/>\r\n");
      out.write("  <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"loginformcssimages/css/animate.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"loginformcssimages/css/animate.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"loginformcssimages/css/Dashboard.css\">\r\n");
      out.write("  \r\n");
      out.write("  <!-- modernizr enables HTML5 elements and feature detects -->\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/modernizr-1.5.min.js\"></script>\r\n");
      out.write("  <link rel=\"shortcut icon\" href=\"images/favicon.ico\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"page1\">\r\n");
      out.write(" ");
 
      
               String username=null;
               try
               {
             
    //  username=request.getAttribute("username");
      username=session.getAttribute("username").toString();
     // out.print("null;lll");
      if(username.equals(null))
      {
    	  
   // response.sendRedirect("login.html");
   /*  rd=request.getRequestDispatcher("/login.html");
    rd.forward(request, response);
    	  request.getRequestDispatcher("login.html").include(request, response); */ 	  
      }
               }
               catch(Exception e)
               {
            	   
            	  // out.print("inside exception");
            	   response.sendRedirect("../login.html");
               }
              
      out.write("\r\n");
      out.write("             \r\n");
      out.write("\r\n");
      out.write("  <div id=\"main\">\r\n");
      out.write("    <header>\r\n");
      out.write("      <div id=\"logo\">\r\n");
      out.write("        <div id=\"logo_text\">\r\n");
      out.write("          <!-- class=\"logo_colour\", allows you to change the colour of the text -->\r\n");
      out.write("          <h1><a href=\"index.html\"><img src=\"images/uniquelogo.png\" height=\"40px\" width=\"40px\">nique<span class=\"logo_colour\">&nbsp;Housing Society</span></a></h1>\r\n");
      out.write("          <h2>Can Change Your Lifestyle.</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("<!--    \t <nav>\r\n");
      out.write("        <ul class=\"sf-menu\" id=\"nav\">\r\n");
      out.write("          <li ><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("          <li class=\"selected\"><a href=\"aboutus.jsp\">About Us</a></li>\r\n");
      out.write("          <li><a href=\"#\">Amenities</a>\r\n");
      out.write("          <ul>\r\n");
      out.write("              <li><a href=\"auditorium.jsp\">Auditorium</a></li>\r\n");
      out.write("              <li><a href=\"gymnasium.jsp\">Gymnasium</a></li>\r\n");
      out.write("              <li><a href=\"emergencyservices.jsp\">Emergency Services</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write(" \r\n");
      out.write("          <li><a href=\"leasesale.jsp\">Lease Or Sale</a></li>\r\n");
      out.write("          <li><a href=\"contact.jsp\">Contact Us</a></li>\r\n");
      out.write("          <li><a href=\"feedback.jsp\"> Feedback</a></li>\r\n");
      out.write("            \r\n");
      out.write("          <li><a href=\"login.html\">Login</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav> -->\r\n");
      out.write("    </header>\r\n");
      out.write("    <div id=\"site_content1\">\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("  \r\n");
      out.write("      <div class=\"content1\">\r\n");
      out.write("        <h1>Welcome to Unique Housing Society</h1>\r\n");
      out.write("        <p align=\"justify\"><span>Welcome</span>\r\n");
 HttpSession hs=request.getSession(); 
      out.write(" \r\n");
      out.write(" ");
 String temp=(String)hs.getAttribute("username");
      out.write('\r');
      out.write('\n');
 out.print(temp); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form>\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("<table width=\"100%\"   style=\"background: transparent;\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><div id=\"container\" align=\"center\"><img src=\"images/adminpanelimages/Login-Registration-icon.png\"/></div></td>\r\n");
      out.write("    <td><div id=\"container\"></div></td>\r\n");
      out.write("    <td><div id=\"container\"></div></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("  <br>\r\n");
      out.write("  <br>\r\n");
      out.write("  <br>\r\n");
      out.write("  <br>\r\n");
      out.write("  <table width=\"100%\">\r\n");
      out.write("   <tr>\r\n");
      out.write("    <td><div id=\"container\"></div></td>\r\n");
      out.write("    <td><div id=\"container\"></div></td>\r\n");
      out.write("    <td><div id=\"container\"></div></td>\r\n");
      out.write("  </tr> \r\n");
      out.write("  </table>\r\n");
      out.write("    <br>\r\n");
      out.write("  <br>\r\n");
      out.write("  <br>\r\n");
      out.write("  <br>\r\n");
      out.write("  <table width=\"100%\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><div id=\"container\"></div></td>\r\n");
      out.write("    <td><div id=\"container\"></div></td>\r\n");
      out.write("    <td><div id=\"container\"></div></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</p>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("       </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("   \r\n");
      out.write("   <footer>\r\n");
      out.write("      <p align=\"left\">Copyright &copy; 2014. | <a href=\"http://www.uniqueideasofttech.com\">Developed By \r\n");
      out.write("      <img src=\"images/logo.png\"> Uniqueidea Software Technologies Pvt Ltd</a></p>\r\n");
      out.write("\t<p align=\"right\"><img src=\"images/Social Media/social-facebook-box-blue-icon.png\">\r\n");
      out.write("     <img src=\"images/Social Media/blog-icon.png\">\r\n");
      out.write("      <img src=\"images/Social Media/linkedin.png\">\r\n");
      out.write("      <img src=\"images/Social Media/YouTube-icon.png\">\r\n");
      out.write("      </p>\r\n");
      out.write("      </footer>     \r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("      </div>\r\n");
      out.write("  <p>&nbsp;</p>\r\n");
      out.write("  <!-- javascript at the bottom for fast page loading -->\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/jquery.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/jquery.easing-sooper.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/jquery.sooperfish.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/jquery.kwicks-1.5.1.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("      $('#images').kwicks({\r\n");
      out.write("        max : 600,\r\n");
      out.write("        spacing : 2\r\n");
      out.write("      });\r\n");
      out.write("      $('ul.sf-menu').sooperfish();\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
